### ISSUE TITLE
version 0.3.0 doesn't work.

### ISSUE THREAD

**Issue by MohannedElfatih** [jamonholmgren/mst-async-storage#9]
I think the new code hasn't been compiled correctly.

**Comment by med4u** [comment]
I also had an issue with version 0.3.0 :
<img width="345" alt="Capture d’écran 2019-10-25 à 01 27 42" src="https://user-images.githubusercontent.com/19374726/67532536-db9d7e00-f6c6-11e9-92ae-0c7ebb460196.png">

, solved by using 0.20

**Comment by taeingyu** [comment]
same here, any update?

**Comment by jamonholmgren** [comment]
Should be fixed in 0.4.0, please test!
